/*** Header File for EDISPM V1.1 ***/
/* Standard OS/2 Declarations */

#ifndef OS2_INCLUDED
   #include <os2.h>
#endif

/* Icons */
#define IDIC_EDISPM 10001
#define IDBM_MSINFO 10002

/* Menu */
#define EDMAINMENU   2000
#define EDCLIENTMENU 2001
#define IDMM_NEW     2002
#define IDMM_FILE    2003
#define IDMM_OPEN    2004
#define IDMM_SAVE    2005
#define IDMM_CLOSE   2006
#define IDMM_EXIT    2007
#define IDMM_TEXT_USERNAME 2008
#define IDMM_VIEW    2101
#define IDMM_HORZ    2102
#define IDMM_VERT    2103
#define IDMM_UPDATE  2104
#define IDMM_HELP    2900
#define IDMM_ABOUT   2901

/* AboutBox-Dialog */
#define NOSELECT -1
#define IDD_ABOUTBOX          50000
#define IDD_ACOPYRIGHTFRAME   50001
#define IDD_APRGICON          50002
#define IDD_APROGRAMFRAME     50003
#define IDC_TEXT              50004

#define DB_RAISED       0x0400
#define DB_DEPRESSED    0x0800

#define IDD_UNAMEBOX                50100
#define IDD_UENTRY                  50101
#define IDD_OPENNEW                 50200
#define IDD_NEUFILE                 50201
#define IDD_NDOCFILENAME            50202
#define IDD_NDOCID                  50203
